// Protestant canon in canonical order, with chapter counts and Chinese
// (和合本) names. Data is factual/public-domain.
const BIBLE_BOOKS = [
  { name: "Genesis", zh: "创世记", chapters: 50, testament: "OT" },
  { name: "Exodus", zh: "出埃及记", chapters: 40, testament: "OT" },
  { name: "Leviticus", zh: "利未记", chapters: 27, testament: "OT" },
  { name: "Numbers", zh: "民数记", chapters: 36, testament: "OT" },
  { name: "Deuteronomy", zh: "申命记", chapters: 34, testament: "OT" },
  { name: "Joshua", zh: "约书亚记", chapters: 24, testament: "OT" },
  { name: "Judges", zh: "士师记", chapters: 21, testament: "OT" },
  { name: "Ruth", zh: "路得记", chapters: 4, testament: "OT" },
  { name: "1 Samuel", zh: "撒母耳记上", chapters: 31, testament: "OT" },
  { name: "2 Samuel", zh: "撒母耳记下", chapters: 24, testament: "OT" },
  { name: "1 Kings", zh: "列王纪上", chapters: 22, testament: "OT" },
  { name: "2 Kings", zh: "列王纪下", chapters: 25, testament: "OT" },
  { name: "1 Chronicles", zh: "历代志上", chapters: 29, testament: "OT" },
  { name: "2 Chronicles", zh: "历代志下", chapters: 36, testament: "OT" },
  { name: "Ezra", zh: "以斯拉记", chapters: 10, testament: "OT" },
  { name: "Nehemiah", zh: "尼希米记", chapters: 13, testament: "OT" },
  { name: "Esther", zh: "以斯帖记", chapters: 10, testament: "OT" },
  { name: "Job", zh: "约伯记", chapters: 42, testament: "OT" },
  { name: "Psalms", zh: "诗篇", chapters: 150, testament: "OT" },
  { name: "Proverbs", zh: "箴言", chapters: 31, testament: "OT" },
  { name: "Ecclesiastes", zh: "传道书", chapters: 12, testament: "OT" },
  { name: "Song of Solomon", zh: "雅歌", chapters: 8, testament: "OT" },
  { name: "Isaiah", zh: "以赛亚书", chapters: 66, testament: "OT" },
  { name: "Jeremiah", zh: "耶利米书", chapters: 52, testament: "OT" },
  { name: "Lamentations", zh: "耶利米哀歌", chapters: 5, testament: "OT" },
  { name: "Ezekiel", zh: "以西结书", chapters: 48, testament: "OT" },
  { name: "Daniel", zh: "但以理书", chapters: 12, testament: "OT" },
  { name: "Hosea", zh: "何西阿书", chapters: 14, testament: "OT" },
  { name: "Joel", zh: "约珥书", chapters: 3, testament: "OT" },
  { name: "Amos", zh: "阿摩司书", chapters: 9, testament: "OT" },
  { name: "Obadiah", zh: "俄巴底亚书", chapters: 1, testament: "OT" },
  { name: "Jonah", zh: "约拿书", chapters: 4, testament: "OT" },
  { name: "Micah", zh: "弥迦书", chapters: 7, testament: "OT" },
  { name: "Nahum", zh: "那鸿书", chapters: 3, testament: "OT" },
  { name: "Habakkuk", zh: "哈巴谷书", chapters: 3, testament: "OT" },
  { name: "Zephaniah", zh: "西番雅书", chapters: 3, testament: "OT" },
  { name: "Haggai", zh: "哈该书", chapters: 2, testament: "OT" },
  { name: "Zechariah", zh: "撒迦利亚书", chapters: 14, testament: "OT" },
  { name: "Malachi", zh: "玛拉基书", chapters: 4, testament: "OT" },
  { name: "Matthew", zh: "马太福音", chapters: 28, testament: "NT" },
  { name: "Mark", zh: "马可福音", chapters: 16, testament: "NT" },
  { name: "Luke", zh: "路加福音", chapters: 24, testament: "NT" },
  { name: "John", zh: "约翰福音", chapters: 21, testament: "NT" },
  { name: "Acts", zh: "使徒行传", chapters: 28, testament: "NT" },
  { name: "Romans", zh: "罗马书", chapters: 16, testament: "NT" },
  { name: "1 Corinthians", zh: "哥林多前书", chapters: 16, testament: "NT" },
  { name: "2 Corinthians", zh: "哥林多后书", chapters: 13, testament: "NT" },
  { name: "Galatians", zh: "加拉太书", chapters: 6, testament: "NT" },
  { name: "Ephesians", zh: "以弗所书", chapters: 6, testament: "NT" },
  { name: "Philippians", zh: "腓立比书", chapters: 4, testament: "NT" },
  { name: "Colossians", zh: "歌罗西书", chapters: 4, testament: "NT" },
  { name: "1 Thessalonians", zh: "帖撒罗尼迦前书", chapters: 5, testament: "NT" },
  { name: "2 Thessalonians", zh: "帖撒罗尼迦后书", chapters: 3, testament: "NT" },
  { name: "1 Timothy", zh: "提摩太前书", chapters: 6, testament: "NT" },
  { name: "2 Timothy", zh: "提摩太后书", chapters: 4, testament: "NT" },
  { name: "Titus", zh: "提多书", chapters: 3, testament: "NT" },
  { name: "Philemon", zh: "腓利门书", chapters: 1, testament: "NT" },
  { name: "Hebrews", zh: "希伯来书", chapters: 13, testament: "NT" },
  { name: "James", zh: "雅各书", chapters: 5, testament: "NT" },
  { name: "1 Peter", zh: "彼得前书", chapters: 5, testament: "NT" },
  { name: "2 Peter", zh: "彼得后书", chapters: 3, testament: "NT" },
  { name: "1 John", zh: "约翰一书", chapters: 5, testament: "NT" },
  { name: "2 John", zh: "约翰二书", chapters: 1, testament: "NT" },
  { name: "3 John", zh: "约翰三书", chapters: 1, testament: "NT" },
  { name: "Jude", zh: "犹大书", chapters: 1, testament: "NT" },
  { name: "Revelation", zh: "启示录", chapters: 22, testament: "NT" },
];

// Named scopes offered in the UI. Each resolves to a set of book names.
const PLAN_SCOPES = {
  "whole-bible": { label: "Whole Bible", filter: () => true },
  "old-testament": { label: "Old Testament", filter: (b) => b.testament === "OT" },
  "new-testament": { label: "New Testament", filter: (b) => b.testament === "NT" },
  "gospels": {
    label: "The Gospels",
    filter: (b) => ["Matthew", "Mark", "Luke", "John"].includes(b.name),
  },
  "psalms-proverbs": {
    label: "Psalms & Proverbs",
    filter: (b) => ["Psalms", "Proverbs"].includes(b.name),
  },
};
